org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=evercrops_dynamictrees
mod_name=EverCrops: Dynamic Trees
mod_license=GNU GPLv3
mod_version=1.0.0
mod_group_id=gottsch
mod_authors=gottsch
mod_description=Dynamic Tree's trees keep growing while you're away.

evercrops_version=3.3.1
evercrops_version_range=[3.3.1,)

# Dynamic Trees
dt_file_id=7661136
#8007613
dt_version_range=[1.7,2.0.0)

# Mixins
mixin=true

archives_base_name=evercrops-dynamictrees-neoforge-1.21.1
